import React from 'react'



function About(){
    return(
        <div className='about'>
        <h1>About Us</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus atque accusamus dicta, commodi quidem quos molestiae. Labore repudiandae aliquam quibusdam itaque reiciendis ex sunt? Cupiditate suscipit quaerat inventore labore unde. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea possimus dolore accusamus laboriosam, odit ducimus numquam debitis aliquid ab eum. Reiciendis, odio! Asperiores eum veniam optio, eveniet nemo magnam ratione.loreem Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ullam dolor quos ab velit eaque nam, fuga voluptatibus aliquid dolore, porro quas voluptatum id neque nobis. Sit recusandae ipsam natus repellendus?Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus atque accusamus dicta, commodi quidem quos molestiae. Labore repudiandae aliquam quibusdam itaque reiciendis ex sunt? Cupiditate suscipit quaerat inventore labore unde. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea possimus dolore accusamus laboriosam, odit ducimus numquam debitis aliquid ab eum. Reiciendis, odio! Asperiores eum veniam optio, eveniet nemo magnam ratione.loreem Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ullam dolor quos ab velit eaque nam, fuga voluptatibus aliquid dolore, porro quas voluptatum id neque nobis. </p><p>Sit recusandae ipsam natus repellendus?Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus atque accusamus dicta, commodi quidem quos molestiae. Labore repudiandae aliquam quibusdam itaque reiciendis ex sunt? Cupiditate suscipit quaerat inventore labore unde. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea possimus dolore accusamus laboriosam, odit ducimus numquam debitis aliquid ab eum. Reiciendis, odio! Asperiores eum veniam optio, eveniet nemo magnam ratione.loreem Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ullam dolor quos ab velit eaque nam, fuga voluptatibus aliquid dolore, porro quas voluptatum id neque nobis. Sit recusandae ipsam natus repellendus?</p><p>Sit recusandae ipsam natus repellendus?Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus atque accusamus dicta, commodi quidem quos molestiae. Labore repudiandae aliquam quibusdam itaque reiciendis ex sunt? Cupiditate suscipit quaerat inventore labore unde. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea possimus dolore accusamus laboriosam, odit ducimus numquam debitis aliquid ab eum. Reiciendis, odio! Asperiores eum veniam optio, eveniet nemo magnam ratione.loreem Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ullam dolor quos ab velit eaque nam, fuga voluptatibus aliquid dolore, porro quas voluptatum id neque nobis. Sit recusandae ipsam natus repellendus?</p>
        </div>
    )
}


export default About